### ISSUE TITLE
Add form to submit doctor's appointments

### ISSUE THREAD

**Issue by jjsoong** [hc-sc/devops-students#2]
The UI needs to include a form that allows users to submit doctor's appointments (date-time selected by the calendar).

**Comment by khalidkanaan** [comment]
Form should include the following fields:
- First Name
- Last Name
- Email (Optional)
- Address:
     1. Street Address
     2. Street Address Line 2 (Optional)
     3. City
     4. Province
     5. Postal Code
     6. Country
- Phone Number
- Reason

**Comment by jjsoong** [comment]
Changed plans
